'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import {
  Button, C, ConfidenceBadge, EmptyState, Field, inputStyle, Kpi, LoadingState,
  MiniSignal, PageHeader, Panel, PercentileBar, ScoreBadge, ScoutingPage, StatusDot, Tabs,
} from '@/app/components/scouting/ScoutingUI'
import { enrichScoutingPool, getGroupLabel, getProfilesForGroup } from '@/data/sportsbase-scouting'
import { formatSportsbaseMetric, getSportsbaseMetric } from '@/data/sportsbase-map'
import { PLAYER_FOOT_OPTIONS, playerFootLabel } from '@/data/player-foot'

const GROUPS = [
  {id:'CB',label:'Zagueiros',icon:'🛡️',positions:'CB,LCB,RCB'}, {id:'FB',label:'Laterais',icon:'↔️',positions:'LB,RB,LWB,RWB'},
  {id:'DM',label:'Volantes',icon:'⚙️',positions:'DMF,CMF,LCMF,RCMF,LDMF,RDMF,CDM,LCDM,RCDM,LDM,RDM,LCM,RCM'},
  {id:'AM',label:'Meias',icon:'🎯',positions:'AMF,CAM,LCAM,RCAM,LM,RM'}, {id:'WG',label:'Extremos',icon:'⚡',positions:'LWF,RWF,LW,RW,LAMF,RAMF,LAM,RAM'},
  {id:'ST',label:'Atacantes',icon:'🔥',positions:'CF,LCF,RCF,SS'},
]
const ALL = {id:'',label:'Todos',icon:'🌐'}
function fmt(v,d=1){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{maximumFractionDigits:d}):'—'}
function leagueLabel(value=''){return String(value).replace('brasileirao-','Brasileirão ').replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function intelligentScore(player){const scout=player._scouting||{};const market=player._market||{};const fit=Number(scout.finalScore)||0;const viability=Number(market.score)||0;return Math.round(fit*.78+viability*.22)}

function RecommendationDrawer({player,onClose,clubGroup}){
  if(!player)return null; const s=player._scouting||{}; const details=s.profileRanking?.[0]?.details||[]
  const groupAverage=key=>{const nums=clubGroup.map(p=>Number(p[key])).filter(Number.isFinite);return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null}
  return <div style={{position:'fixed',inset:0,zIndex:80,background:'rgba(10,31,19,.5)',display:'flex',justifyContent:'flex-end'}} onMouseDown={event=>event.target===event.currentTarget&&onClose()}>
    <div style={{width:'min(620px,96vw)',height:'100%',overflow:'auto',background:'#fff',boxShadow:'-16px 0 50px rgba(0,0,0,.18)'}}>
      <div style={{padding:20,borderBottom:`1px solid ${C.line}`,display:'flex',justifyContent:'space-between'}}><div><h2 style={{fontSize:19,color:C.ink}}>{player.nome}</h2><p style={{fontSize:10.5,color:C.muted,marginTop:4}}>{player.equipa} · {leagueLabel(player._liga)} · {player.posicao} · Pé {playerFootLabel(player.pe)} · {fmt(player.minutos,0)} min</p></div><button onClick={onClose} style={{border:0,background:'none',fontSize:22,cursor:'pointer'}}>×</button></div>
      <div style={{padding:20,display:'grid',gap:13}}>
        <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:8}}><MiniSignal label="Prioridade" value={s.finalScore}/><MiniSignal label="Perfil" value={s.profileScore} tone={C.purple}/><MiniSignal label="Fit tático" value={s.tacticalScore} tone={C.blue}/><MiniSignal label="Viabilidade" value={player._market?.score||0} tone={C.amber}/><MiniSignal label="Amostra" value={s.confidence?.label||'—'} tone={s.confidence?.color||C.amber}/></div>
        <Panel title="Interpretação para scouting" subtitle="Dados organizam a pergunta; vídeo e contexto validam a resposta"><p style={{fontSize:11,color:C.ink,lineHeight:1.55}}><b>{s.profile}</b> como perfil dominante, com prioridade contextual de {s.finalScore}/100. Mercado: {player._market?.label || 'compatível'}. O candidato deve ser observado na função real, especialmente em tomada de decisão, comportamento sem bola e adaptação ao modelo coletivo.</p></Panel>
        <Panel title="Métricas do perfil" subtitle="Percentil no mercado e referência média do Confiança"><div style={{display:'grid',gap:12}}>{details.filter(item=>item.percentile!==null).slice(0,9).map(item=>{const metric=getSportsbaseMetric(item.key)||item;const internal=groupAverage(item.key);return <div key={item.key}><PercentileBar label={item.label} value={item.percentile} raw={formatSportsbaseMetric(item.value,metric)} color={item.percentile>=70?C.green:item.percentile>=45?C.amber:C.red}/>{internal!=null&&<p style={{fontSize:8.5,color:C.muted,margin:'3px 0 0 129px'}}>Confiança: {formatSportsbaseMetric(internal,metric)}</p>}</div>})}</div></Panel>
        <Panel title="Roteiro de validação"><div style={{display:'grid',gap:8}}>{(s.strengths||[]).map(item=><div key={`s-${item.key}`} style={{padding:9,borderRadius:9,background:C.green2}}><b style={{fontSize:10,color:C.ink}}>{item.label}</b><p style={{fontSize:9,color:C.green,marginTop:2}}>P{item.percentile}: validar recorrência, espaço e adversário.</p></div>)}{(s.concerns||[]).slice(0,3).map(item=><div key={`c-${item.key}`} style={{padding:9,borderRadius:9,background:'#fff7eb'}}><b style={{fontSize:10,color:C.ink}}>{item.label}</b><p style={{fontSize:9,color:C.amber,marginTop:2}}>P{item.percentile}: checar se é limitação individual ou contexto.</p></div>)}</div></Panel>
        <div style={{display:'flex',justifyContent:'flex-end',gap:8}}><Link href={`/comparacao?player=${encodeURIComponent(player.nome)}&liga=${encodeURIComponent(player._liga||'')}`}><Button variant="secondary">📊 Comparar</Button></Link><Link href="/centro-recrutamento"><Button>🎯 Criar foco / pipeline</Button></Link></div>
      </div>
    </div>
  </div>
}

export default function RecommendationsPage(){
  const [group,setGroup]=useState('AM'); const [mode,setMode]=useState('tactical'); const [market,setMarket]=useState([]); const [clubData,setClubData]=useState(null)
  const [leagues,setLeagues]=useState([]); const [league,setLeague]=useState(''); const [profile,setProfile]=useState(''); const [foot,setFoot]=useState(''); const [age,setAge]=useState(28); const [minutes,setMinutes]=useState(450)
  const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState(null)
  const groupDef=GROUPS.find(item=>item.id===group)||GROUPS[0]; const profiles=Object.keys(getProfilesForGroup(group))
  useEffect(()=>{Promise.all([fetch('/api/club-sportsbase').then(r=>r.json()),fetch('/api/ligas-v2/jogadores?limit=1&contexto=confianca').then(r=>r.json())]).then(([g,m])=>{setClubData(g);setLeagues(m.ligas||[])}).catch(()=>{}).finally(()=>setLoading(false))},[])
  useEffect(()=>{
    if(!clubData)return; let cancelled=false;setLoading(true)
    const params=new URLSearchParams({posicao:groupDef.positions,limit:'500',minMin:String(minutes),idadeMax:String(age),ordem:'minutos',dir:'desc',contexto:'confianca',somenteViaveis:'1',canonical:'0'});if(league)params.set('liga',league);if(foot)params.set('pe',foot)
    fetch(`/api/ligas-v2/jogadores?${params}`).then(r=>r.json()).then(json=>{if(cancelled)return;const candidates=(json.jogadores||[]).filter(p=>String(p.equipa||'').toLowerCase()!=='confianca'&&p._market?.actionable!==false);const enriched=enrichScoutingPool(candidates,clubData.model||clubData.summary?.model||null,minutes).map(player=>({...player,_scouting:{...player._scouting,dataFit:player._scouting.finalScore,finalScore:intelligentScore(player)}})).sort((a,b)=>mode==='profile'?b._scouting.profileScore-a._scouting.profileScore:b._scouting.finalScore-a._scouting.finalScore);setMarket(enriched)}).catch(()=>setMarket([])).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}
  },[group,league,foot,age,minutes,clubData,mode])
  const clubGroup=useMemo(()=>enrichScoutingPool((clubData?.players||[]).filter(p=>p&&groupDef.positions.split(',').some(code=>String(p.posicao||'').split(',').map(x=>x.trim()).includes(code))),clubData?.model||null,0),[clubData,group])
  const visible=useMemo(()=>market.filter(player=>(!profile||player._scouting.profile===profile)&&`${player.nome} ${player.equipa}`.toLowerCase().includes(search.toLowerCase())).slice(0,80),[market,profile,search])
  const squadAvg=clubGroup.length?Math.round(clubGroup.reduce((s,p)=>s+(p._scouting?.finalScore||0),0)/clubGroup.length):0
  const topProfile=clubGroup.reduce((acc,p)=>{const key=p._scouting?.profile;if(key)acc[key]=(acc[key]||0)+1;return acc},{})
  const dominantSquad=Object.entries(topProfile).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Sem referência'

  return <ScoutingPage maxWidth={1500}>
    <PageHeader title="Recomendações para o Confiança" subtitle="O ranking combina desempenho por função, modelo de jogo do Confiança e viabilidade real para um clube em reconstrução para a Série D de 2027, com foco no acesso à Série C. Mercados de referência ou economicamente incompatíveis não entram automaticamente." status={<StatusDot color={clubData?.model?.sampleGames?C.green:C.amber}>{clubData?.model?.sampleGames||0} jogos de referência</StatusDot>} actions={<><Link href="/elenco"><Button variant="secondary">🟢 Referência Confiança</Button></Link><Link href="/centro-recrutamento"><Button>🎯 Centro de Recrutamento</Button></Link></>}/>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10,marginBottom:14}}><Kpi label="Modelo de jogo" value={clubData?.model?.identity?'Ativo':'Pendente'} sub={clubData?.model?.identity||'importe a planilha coletiva'} icon="🧠"/><Kpi label="Grupo analisado" value={getGroupLabel(group)} sub={`${clubGroup.length} atletas no elenco`} icon="🧭" tone={C.blue}/><Kpi label="Referência interna" value={squadAvg} sub={`perfil mais presente: ${dominantSquad}`} icon="🟢" tone={C.purple}/><Kpi label="Mercado compatível" value={visible.length} sub={`viáveis · ≥${minutes} min · até ${age} anos`} icon="🌐" tone={C.amber}/></div>
    <div className="scout-two-col" style={{display:'grid',gridTemplateColumns:'270px minmax(0,1fr)',gap:14,alignItems:'start'}}>
      <div style={{display:'grid',gap:12}}><Panel title="Posição / função" bodyStyle={{padding:9}}><div style={{display:'grid',gap:5}}>{GROUPS.map(item=><button key={item.id} onClick={()=>{setGroup(item.id);setProfile('')}} style={{padding:'9px 10px',borderRadius:9,border:`1px solid ${group===item.id?C.green:C.line}`,background:group===item.id?C.green2:'#fff',color:group===item.id?C.green:C.muted,fontSize:10.5,fontWeight:850,textAlign:'left',cursor:'pointer'}}>{item.icon} {item.label}</button>)}</div></Panel><Panel title="Recorte de mercado"><div style={{display:'grid',gap:10}}><Field label="Liga"><select value={league} onChange={e=>setLeague(e.target.value)} style={inputStyle}><option value="">Todas</option>{leagues.map(item=><option key={item} value={item}>{leagueLabel(item)}</option>)}</select></Field><Field label="Perfil funcional"><select value={profile} onChange={e=>setProfile(e.target.value)} style={inputStyle}><option value="">Todos</option>{profiles.map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Pé preferido"><select value={foot} onChange={e=>setFoot(e.target.value)} style={inputStyle}>{PLAYER_FOOT_OPTIONS.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><Field label={`Idade máxima: ${age}`}><input type="range" min="18" max="38" value={age} onChange={e=>setAge(Number(e.target.value))}/></Field><Field label={`Minutos mínimos: ${minutes}`}><input type="range" min="0" max="1200" step="50" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></Field><Field label="Buscar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Atleta ou clube" style={inputStyle}/></Field></div></Panel><Panel title="Necessidades do modelo" subtitle="Dimensões com menor score coletivo"><div style={{display:'grid',gap:7}}>{(clubData?.model?.needs||[]).map(item=><div key={item.key} style={{padding:9,borderRadius:9,background:'#fff7eb',border:'1px solid #f1dfbd'}}><strong style={{fontSize:10,color:C.ink}}>{item.label}</strong><p style={{fontSize:9,color:C.amber,marginTop:2}}>{item.score}/100 · oportunidade de ganho</p></div>)}</div></Panel></div>
      <div style={{display:'grid',gap:12}}><Tabs active={mode} onChange={setMode} items={[{id:'tactical',label:'Encaixe tático Confiança',icon:'🧩',flex:1},{id:'profile',label:'Perfil funcional',icon:'🧬',flex:1}]}/><Panel title={mode==='tactical'?'Ranking de encaixe':'Ranking por perfil'} subtitle={mode==='tactical'?'Desempenho + modelo Confiança + viabilidade competitiva e financeira':'Compara o atleta com pares do mesmo grupo posicional'} bodyStyle={{padding:0}}>{loading?<LoadingState text="Cruzando função, modelo e mercado..."/>:!visible.length?<EmptyState icon="🧭" title="Nenhum atleta no recorte" text="Revise posição, idade, minutos, liga ou perfil."/>:<div className="scout-scroll" style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:980}}><thead><tr style={{background:'#f6faf7',fontSize:9,color:C.muted,textTransform:'uppercase'}}>{['#','Atleta / contexto','Perfil','Prioridade','Mercado','Amostra','Principais sinais','Leitura'].map(label=><th key={label} style={{padding:'11px 12px',textAlign:'left',borderBottom:`1px solid ${C.line}`}}>{label}</th>)}</tr></thead><tbody>{visible.map((player,index)=>{const s=player._scouting;return <tr key={`${player.nome}-${player.equipa}`} style={{borderBottom:`1px solid #edf3ef`}}><td style={{padding:12,color:C.green,fontWeight:900,fontSize:11}}>{index+1}º</td><td style={{padding:12}}><button onClick={()=>setSelected(player)} style={{border:0,background:'none',padding:0,textAlign:'left',cursor:'pointer'}}><strong style={{fontSize:11.5,color:C.ink}}>{player.nome}</strong><p style={{fontSize:9.5,color:C.muted,marginTop:3}}>{player.equipa} · {leagueLabel(player._liga)} · {player.idade||'—'} anos · {fmt(player.minutos,0)} min</p></button></td><td style={{padding:12}}><strong style={{fontSize:10.5,color:C.ink}}>{s.profile}</strong><p style={{fontSize:9,color:C.muted,marginTop:2}}>{s.secondaryProfile||'—'} · {s.secondaryScore}</p></td><td style={{padding:12}}><ScoreBadge value={mode==='profile'?s.profileScore:s.finalScore}/><p style={{fontSize:8.5,color:C.muted,marginTop:4}}>dados {s.dataFit||s.finalScore} · tático {s.tacticalScore}</p></td><td style={{padding:12}}><strong style={{fontSize:9.5,color:player._market?.band==='A'?C.green:C.amber}}>{player._market?.band||'B'} · {player._market?.score||'—'}</strong><p style={{fontSize:8.2,color:C.muted,marginTop:3,maxWidth:150}}>{player._market?.label||'Mercado compatível'}</p></td><td style={{padding:12}}><ConfidenceBadge confidence={s.confidence}/></td><td style={{padding:12,maxWidth:310}}><div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{s.strengths.slice(0,3).map(item=><span key={item.key} style={{fontSize:8.5,padding:'4px 6px',borderRadius:6,background:C.green2,color:C.green,fontWeight:800}}>{item.label} P{item.percentile}</span>)}</div></td><td style={{padding:12}}><Button variant="secondary" onClick={()=>setSelected(player)} style={{padding:'7px 9px'}}>Abrir</Button></td></tr>})}</tbody></table></div>}</Panel></div>
    </div>
    {selected&&<RecommendationDrawer player={selected} onClose={()=>setSelected(null)} clubGroup={clubGroup}/>} 
  </ScoutingPage>
}
